CURRENT_APR = ENV.fetch('CURRENT_APR').to_f
CURRENT_LOAN_AMOUNT = ENV.fetch('CURRENT_LOAN_AMOUNT').to_f
CURRENT_DURATION = ENV.fetch('CURRENT_DURATION').to_f
CURRENT_VALUE = ENV.fetch('CURRENT_VALUE').to_f
REFI_APR = ENV.fetch('REFI_APR').to_f
REFI_LOAN_AMOUNT = ENV.fetch('REFI_LOAN_AMOUNT').to_f
REFI_DURATION = ENV.fetch('REFI_DURATION').to_f
REFI_VALUE = ENV.fetch('REFI_VALUE').to_f
